### ISSUE TITLE
Takedown Your Bun Extension

### ISSUE THREAD

**Issue by elibroftw** [Penggeor/bun#2]
Bun has an official extension but this appears before it when searching for "bun" in the VS Code extensions. Please take down your extension, it's not helping people.

**Comment by wukaipeng-dev** [comment]
@elibroftw Thank you for your love for bun but I can't accept your suggestion because my extension is different from the official that mine is to let people quickly execute their js/ts files by bun. The extension is frequently used by myself and many other people.

If you are confused by name, you have to read the Readme before using any vscode extension. Besides, you can open an issue to the github repository. The bun extension is also an open source that does not earn any money.
